### ISSUE TITLE
lambda@edgeのパッケージサイズ1MB制限対応

### ISSUE THREAD

**Issue by SatoKeisuke** [PERMAN/cloudfront-auth#19]
npmパッケージを更新したことにより、パッケージサイズ（zip化した時）が1MBを超えてしまい、cloudfrontにlambda functionを紐付けられなくなった。

現状紐付けるためには、不要なパッケージを削除するなどの対応が必要

**Comment by SatoKeisuke** [comment]
圧縮率を上げてみる

**Comment by SatoKeisuke** [comment]
圧縮率変えてみましたが、サイズは変わりませんでした。。

**Comment by okzk** [comment]
今どきwebpackでもないとは思うけど、webpackかそのaltenativeでビルドしたらだいぶ小さくなるかも？
(未使用コードがゴリっとなくなってくれるハズ？？？)

最近だとviteなのかな？？？

**Comment by yasuda-naoki-2010** [comment]
NODE_ENV=productionになっていないなんてことは。。？

**Comment by yasuda-naoki-2010** [comment]
https://github.com/PERMAN/cloudfront-auth/blob/main/build.sh#L3
あ、直接オプションで指定してましたね。。

**Comment by SatoKeisuke** [comment]
おふたりともコメントありがとうございます

> 今どきwebpackでもないとは思うけど、webpackかそのaltenativeでビルドしたらだいぶ小さくなるかも？
(未使用コードがゴリっとなくなってくれるハズ？？？)

なるほど、そうなんですね
時間ができた時に調べて試してみます

**Comment by SatoKeisuke** [comment]
https://github.com/PERMAN/cloudfront-auth/pull/21
